# -*- coding: utf-8 -*-
"""14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reoY6tgu6OSlzJo0QY_A5KDjbruaC8AD
"""

import numpy as np
import matplotlib.pyplot as plt

# ============================================================================
# ΙΔΕΑ 14: Semantic ADB με class-dependent safety margins
# ============================================================================

# ----------------------------------------------------------------------------
# 1. Baseline μοντέλο
# ----------------------------------------------------------------------------
# Στο baseline θεωρούμε ότι το ADB χρησιμοποιεί σταθερό safety margin
# για όλα τα αντικείμενα, ανεξάρτητα από το είδος τους.
#
# m_base = m0
#
# όπου m0 = σταθερό γωνιακό περιθώριο σκίασης (σε μοίρες).
# ----------------------------------------------------------------------------

m0 = 2.0  # σταθερό baseline margin σε μοίρες

# ----------------------------------------------------------------------------
# 2. Προτεινόμενο semantic μοντέλο
# ----------------------------------------------------------------------------
# Ορίζουμε:
#
#   m(c, d) = m_c * (1 + alpha(d))
#
# όπου:
#   c  = κατηγορία αντικειμένου
#   d  = απόσταση σε μέτρα
#   m_c = βασικό margin ανά κατηγορία
#   alpha(d) = distance-dependent scaling factor
#
# Επιλέγουμε:
#
#   alpha(d) = max(0.5, 1 - d/200)
#
# Έτσι:
# - σε μικρή απόσταση αυξάνει το margin
# - σε μεγάλη απόσταση μειώνεται αλλά δεν μηδενίζεται
# ----------------------------------------------------------------------------

def alpha_distance(distance_m: float) -> float:
    """Distance-dependent scaling factor."""
    return max(0.5, 1.0 - distance_m / 200.0)

def semantic_margin(obj_class: str, distance_m: float) -> float:
    """
    Υπολογισμός semantic safety margin ανάλογα με την κατηγορία αντικειμένου
    και την απόσταση.
    """
    base_margins = {
        "vehicle": 2.0,
        "pedestrian": 4.0,
        "cyclist": 3.5,
    }

    m_c = base_margins.get(obj_class, 2.0)
    return m_c * (1.0 + alpha_distance(distance_m))

# ----------------------------------------------------------------------------
# 3. Υπολογισμός margins σε εύρος αποστάσεων
# ----------------------------------------------------------------------------
distances = np.linspace(10, 150, 100)

margin_vehicle = np.array([semantic_margin("vehicle", d) for d in distances])
margin_pedestrian = np.array([semantic_margin("pedestrian", d) for d in distances])
margin_cyclist = np.array([semantic_margin("cyclist", d) for d in distances])

baseline_margin = np.full_like(distances, m0)

# ----------------------------------------------------------------------------
# 4. Ενδεικτικό metric σύγκρισης
# ----------------------------------------------------------------------------
# Για να συγκρίνουμε baseline vs semantic πολιτική, ορίζουμε έναν απλό
# "συντηρητικό δείκτη προστασίας":
#
#   gain(c, d) = m_semantic(c, d) / m_base
#
# Αν gain > 1, τότε η semantic πολιτική είναι πιο συντηρητική από το baseline.
# ----------------------------------------------------------------------------

gain_vehicle = margin_vehicle / baseline_margin
gain_pedestrian = margin_pedestrian / baseline_margin
gain_cyclist = margin_cyclist / baseline_margin

print("=" * 72)
print("ΙΔΕΑ 14 — Semantic ADB με class-dependent safety margins")
print("=" * 72)
print(f"Baseline σταθερό margin: {m0:.2f}°")
print()
print("Ενδεικτικές τιμές:")
for d in [20, 50, 100, 150]:
    mv = semantic_margin("vehicle", d)
    mp = semantic_margin("pedestrian", d)
    mc = semantic_margin("cyclist", d)
    print(f"Απόσταση {d:>3} m | vehicle={mv:.2f}° | pedestrian={mp:.2f}° | cyclist={mc:.2f}°")

# ----------------------------------------------------------------------------
# 5. Διαγράμματα
# ----------------------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Διάγραμμα 1: margin vs distance
ax = axes[0]
ax.plot(distances, baseline_margin, label="Baseline σταθερό margin", linewidth=2)
ax.plot(distances, margin_vehicle, label="Όχημα", linewidth=2)
ax.plot(distances, margin_pedestrian, label="Πεζός", linewidth=2)
ax.plot(distances, margin_cyclist, label="Ποδηλάτης", linewidth=2)

ax.set_title("Semantic safety margins ως προς την απόσταση")
ax.set_xlabel("Απόσταση (m)")
ax.set_ylabel("Margin σκίασης (°)")
ax.grid(alpha=0.3)
ax.legend()

# Διάγραμμα 2: relative protection gain
ax = axes[1]
ax.plot(distances, gain_vehicle, label="Όχημα", linewidth=2)
ax.plot(distances, gain_pedestrian, label="Πεζός", linewidth=2)
ax.plot(distances, gain_cyclist, label="Ποδηλάτης", linewidth=2)
ax.axhline(1.0, color="black", linestyle="--", linewidth=1)

ax.set_title("Σχετικό κέρδος προστασίας έναντι baseline")
ax.set_xlabel("Απόσταση (m)")
ax.set_ylabel("Semantic / Baseline")
ax.grid(alpha=0.3)
ax.legend()

plt.tight_layout()
plt.show()

"""Προτεινόμενη βελτίωση φωτισμού ADB:
Στο baseline σύστημα θεωρείται μία ενιαία πολιτική σκίασης για όλους τους στόχους. Ως βελτίωση προτείνεται semantic ADB, στο οποίο το γωνιακό περιθώριο σκίασης δεν είναι σταθερό αλλά εξαρτάται τόσο από την κατηγορία του αντικειμένου όσο και από την απόστασή του. Συγκεκριμένα, για πεζούς και ποδηλάτες επιλέγεται μεγαλύτερο safety margin σε σχέση με τα οχήματα, ενώ το περιθώριο αυξάνεται όταν η απόσταση μικραίνει. Με αυτόν τον τρόπο, το σύστημα αποκτά context-aware συμπεριφορά και μπορεί να προσφέρει αυξημένη προστασία από θάμβωση σε πιο ευάλωτους χρήστες του δρόμου. Η προτεινόμενη μέθοδος αποτελεί semantic επέκταση του ADB μέρους του baseline paper και αξιολογείται σε επίπεδο αναλυτικού/εννοιολογικού μοντέλου
"""