# -*- coding: utf-8 -*-
"""17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reoY6tgu6OSlzJo0QY_A5KDjbruaC8AD
"""

import numpy as np
import matplotlib.pyplot as plt

# ============================================================================
# ΙΔΕΑ 17 — Frequency Hopping FMCW
# ============================================================================

# ----------------------------------------------------------------------------
# 1. Πιθανότητα παρεμβολής
# ----------------------------------------------------------------------------

def collision_probability(K, N_hops):
    """
    Υπολογίζει την πιθανότητα σύγκρουσης FMCW σημάτων.

    K       : αριθμός οχημάτων
    N_hops  : αριθμός διαθέσιμων frequency slots
    """
    return 1 - (1 - 1/N_hops)**K

# ----------------------------------------------------------------------------
# 2. Sweep αριθμού οχημάτων
# ----------------------------------------------------------------------------

vehicles = np.arange(1, 11)

# baseline (χωρίς hopping - απλοποιημένο μοντέλο)
p_baseline = np.clip(0.18 * vehicles, 0, 0.95)

# με hopping
N_hops = 64
p_hopping = np.array([collision_probability(v, N_hops) for v in vehicles])

# ----------------------------------------------------------------------------
# 3. Εκτύπωση αποτελεσμάτων
# ----------------------------------------------------------------------------

print("="*60)
print("ΙΔΕΑ 17 — Frequency Hopping FMCW")
print("="*60)

for v in [2, 5, 8]:
    p_std = np.clip(0.18 * v, 0, 0.95)
    p_hop = collision_probability(v, N_hops)
    print(f"Οχήματα: {v} | baseline={p_std:.3f} | hopping={p_hop:.3f}")

# ----------------------------------------------------------------------------
# 4. Plot
# ----------------------------------------------------------------------------

plt.figure(figsize=(8,5))

plt.plot(vehicles, p_baseline, marker='o', label="Baseline FMCW")
plt.plot(vehicles, p_hopping, marker='s', linestyle='--', label="Frequency hopping")

plt.xlabel("Αριθμός οχημάτων")
plt.ylabel("Πιθανότητα παρεμβολής")
plt.title("Μείωση interference με frequency hopping")
plt.grid(alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

"""Η παρουσία πολλών οχημάτων σε περιβάλλον ISAC οδηγεί σε mutual interference μεταξύ FMCW σημάτων, γεγονός που υποβαθμίζει την ακρίβεια ανίχνευσης και την αξιοπιστία επικοινωνίας. Ως βελτίωση προτείνεται η χρήση frequency hopping FMCW, όπου κάθε όχημα επιλέγει δυναμικά συχνότητα από ένα σύνολο διαθέσιμων καναλιών. Η πιθανότητα σύγκρουσης μπορεί να προσεγγιστεί από τη σχέση
P=1−(1−1/N) όπου K είναι ο αριθμός των οχημάτων και
𝑁 το πλήθος των διαθέσιμων καναλιών. Η ανάλυση δείχνει σημαντική μείωση της πιθανότητας παρεμβολής, γεγονός που καθιστά τη μέθοδο ιδιαίτερα αποτελεσματική σε πυκνά περιβάλλοντα κυκλοφορίας
"""