# -*- coding: utf-8 -*-
"""Wideband FMCW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reoY6tgu6OSlzJo0QY_A5KDjbruaC8AD
"""

import numpy as np
import matplotlib.pyplot as plt

# ============================================================================
# ΙΔΕΑ 7 — Wideband FMCW
# ============================================================================

c = 3e8  # speed of light

# ----------------------------------------------------------------------------
# 1. Range resolution
# ----------------------------------------------------------------------------
def range_resolution(B):
    """
    ΔR = c / (2B)
    """
    return c / (2 * B)

# ----------------------------------------------------------------------------
# 2. CRLB-like metric
# ----------------------------------------------------------------------------
def sigma_range(B, snr_linear):
    """
    σ_R ∝ 1 / (B * sqrt(SNR))
    """
    return 1 / (B * np.sqrt(snr_linear))

# ----------------------------------------------------------------------------
# 3. Sweep bandwidth
# ----------------------------------------------------------------------------
B_values = np.array([5e9, 10e9, 20e9, 50e9, 100e9])
snr = 10  # linear SNR

resolutions = range_resolution(B_values)
sigmas = sigma_range(B_values, snr)

# ----------------------------------------------------------------------------
# 4. Print results
# ----------------------------------------------------------------------------
print("="*60)
print("ΙΔΕΑ 7 — Wideband FMCW")
print("="*60)

for B, r in zip(B_values, resolutions):
    print(f"B = {B/1e9:.0f} GHz → ΔR = {r*100:.2f} cm")

# ----------------------------------------------------------------------------
# 5. Plot
# ----------------------------------------------------------------------------
plt.figure(figsize=(8,5))

plt.plot(B_values/1e9, resolutions*100, marker='o', label="Resolution (cm)")
plt.plot(B_values/1e9, sigmas/np.max(sigmas)*100, marker='s', label="Normalized error")

plt.xlabel("Bandwidth (GHz)")
plt.ylabel("cm (scaled)")
plt.title("Επίδραση bandwidth στο FMCW")
plt.grid(alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

"""Η ακρίβεια εκτίμησης απόστασης σε συστήματα FMCW εξαρτάται άμεσα από το διαθέσιμο εύρος ζώνης. Συγκεκριμένα, η θεωρητική ανάλυση δείχνει ότι η διακριτική ικανότητα στο εύρος δίνεται από τη σχέση

ΔR=c/2B
, γεγονός που υποδηλώνει ότι η αύξηση του bandwidth οδηγεί σε βελτίωση της χωρικής ανάλυσης. Επιπλέον, η διακύμανση της εκτίμησης μειώνεται με το τετράγωνο του bandwidth, σύμφωνα με αποτελέσματα τύπου CRLB. Επομένως, η αύξηση του εύρους ζώνης αποτελεί έναν άμεσο και αποτελεσματικό τρόπο βελτίωσης της απόδοσης του συστήματος sensing.
"""